### ISSUE TITLE
/function expansion:_commands/goto/space, /function expansion:_commands/goto/earth broken

### ISSUE THREAD

**Issue by davidCMs** [VonLeipenstein/the-expansion-DATAPACK#5]
/function expansion:_commands/goto/space teleports you to space but then your imidiatly kicked back to the owerwold to position 
"23 448 23"

**Comment by davidCMs** [comment]
seams to depend on the postion where the command was executed

**Comment by davidCMs** [comment]
/function expansion:_commands/goto/earth just straight up dosnt work anywhere

**Comment by davidCMs** [comment]
all other goto commands work

**Comment by VonLeipenstein** [comment]
fixed, was using spreadplayers which doesnt always find a valid position
