### ISSUE TITLE
graviry not updating correctly while entering planets as a player

### ISSUE THREAD

**Issue by davidCMs** [VonLeipenstein/the-expansion-DATAPACK#6]
entering planets aloan without a spaceship will not remove graviy tags

![image](https://github.com/user-attachments/assets/3d806ba1-611b-419c-b52e-46f18faf4f0a)

**Comment by davidCMs** [comment]
might be my issue as i entered moon from space that i enterd with  /tp in

**Comment by VonLeipenstein** [comment]
confirmed, caused by a a rogue exp.has_changed_gravity tag
